### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by bondeanikets** [loopj/jquery-tokeninput#873]
**I am using jquery-tokeninput. But when I pass the path to my script (that returns list of dictionaries) to 'tokenInput' function, I get the following error. Kindly help.**

Traceback (most recent call last):
  File "/usr/local/cai_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/cai_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 142, in __call__
    response = self.process_response(request, response)
  File "/usr/local/cai_venv/lib/python3.6/site-packages/django/middleware/clickjacking.py", line 32, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'list' object has no attribute 'get'
2017-09-17 16:51:13,463 : ERROR : Internal Server Error: /brand/topic_trends/brand/topic_trends
Traceback (most recent call last):
  File "/usr/local/cai_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/cai_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 142, in __call__
    response = self.process_response(request, response)
  File "/usr/local/cai_venv/lib/python3.6/site-packages/django/middleware/clickjacking.py", line 32, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'list' object has no attribute 'get'

**The return object of my script looks like this:**

[     
      {"id": "146", "name": "146"}, 
      {"id": "cheveron", "name": "cheveron"}, 
      {"id": "ineligible", "name": "ineligible"}, 
      {"id": "1700sq", "name": "1700sq"}, 
      {"id": "_very", "name": "_very"}, 
      {"id": "hipaa", "name": "hipaa"}      
]

**Comment by bondeanikets** [comment]
I figured it out:
The solution was to return a 'HttpResponse' instead of JSON like:

**return HttpResponse(data, content_type='application/json')**
